version: 2.1
orbs:
  node: circleci/node@4.2.0

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages
      - run: npm run test -- --json --outputFile /tmp/test-results/jest/results.json
      - store_test_results:
          path: /tmp/test-results
      - run: npm run build
      - store_artifacts:
          path: build
          destination: artifact-file

workflows:
  my-flow:
    jobs:
      - build

