version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm ci
      - run: npm run test -- --json --outputFile /tmp/test_results.json
      - store_test_results:
          path: /tmp/test_results.json
      - run: npm run build
      - store_artifacts:
          path: build
          destination: artifact-file

workflows:
  my-flow:
    jobs:
      - build

