version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  build:
    docker: 
      - image: circleci/node:14
    steps:
      - run:
          name: test
          command: node --version
workflows:
  my-flow:
    jobs:
      - build
      - node/test:
          version: 14.15.4

