version: 2.1
orbs:
  node: circleci/node@4.2.0

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: /tmp/test-results/jest/
      - store_test_results:
          path: /tmp/test-results
      - run: npm run build
      - store_artifacts:
          path: build
          destination: artifact-file
  deploy:
    docker:
      - image: cimg/node:lts
    steps:
      -run: ls build

workflows:
  my-flow:
    jobs:
      - build
      - deploy:
          requires: build
