version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  build:
    docker:
      - image: cimg/node:14
    steps:
      - checkout
      - run:
          name: build
          command: npm run build
      - run:
          name: echo npm version
          command: npm version
workflows:
  my-flow:
    jobs:
      - build:
          requires: ["node/test"]
      - node/test:
          version: 14.15.4

