version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-s3: circleci/aws-s3@2.0.0

parameters:
  my-param:
    type: string
    default: 'XXX'

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages
      - run: npm run test:ci      
      - store_test_results:
          path: ./results
      - run: npm run build
      - store_artifacts:
          path: ./reports
          destination: reports
      - aws-s3/sync:
          from: ./build
          to: 's3://atombrenner/circleci/build/<< pipeline.env.CIRCLE_BUILD_NUM >>'
          arguments: '--storage-class STANDARD_IA --delete'

  deploy-to-stage:
    docker:
      - image: cimg/base:2020.01
    steps: 
      - run: echo "Deploy ${CIRCLE_BUILD_NUM} to Stage"
      # - aws-s3/sync:
      #     from: s3://atombrenner/circleci/build/${CIRCLE_BUILD_NUM}
      #     to: s3://atombrenner/circleci/stage

  deploy-to-prod:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "Dummy Deploy ${CIRCLE_BUILD_NUM}"

workflows:
  continuous-delivery:
    jobs:
      - build
      - deploy-to-stage:
          requires:
            - build
      - approve-prod-deploy:
          type: approval
          requires:
            - deploy-to-stage
      - deploy-to-prod:
          requires:
            - approve-prod-deploy
