version: 2.1
#orbs:
#  node: circleci/node@4.2.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm ci
      - run:
          name: test
          command: npm run test
      - run:
          name: build
          command: npm run build
      - store_artifacts:
          path: build
          destination: artifact-file
workflows:
  my-flow:
    jobs:
      - build

#
